name: Run Unit Tests

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 8 * * 2"
  
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9.2]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python test_data.py
